### ISSUE TITLE
add description and running instructions to readme

### ISSUE THREAD

**Issue by yochannah** [intermine/sequence-alignment-service#2]
future us will thank now us for making it easy to figure out what to do to make this run, and why we want to do it :)

**Comment by AdrianBZG** [comment]
@yochannah For context, the reason of this small service is that the sequences of the proteins fetched from InterMine are not aligned (and we need them aligned to make sense when shown in the MSA viewer, as it just shows sequences without aligning them), so we needed to find some alignment service that either 1) has an API to call it from JS or 2) is a JS library. We didn't find a suitable tool with 1), so we went with 2).

**Comment by yochannah** [comment]
Sounds reasonable! Shall we deploy this as ~sequencealign.apps.intermine.org~ sequencealignment.apps.intermine.org and hardcode to that url rather than localhost?

**Comment by AdrianBZG** [comment]
@yochannah That sounds like the way to go! 👍 (sequencealignment.apps.intermine.org)

**Comment by heralden** [comment]
Fixed with #3

**Comment by heralden** [comment]
I should note that this has been deployed on *sequencealignment.apps.intermine.org* like you noted, and https://github.com/intermine/bluegenes-msa-viewer has been updated with the hardcoded url.
